#define DLL_NAME "version"
#include "hijack.h"
PLACEHOLDER __place_holder_1() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_2() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_3() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_4() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_5() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_6() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_7() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_8() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_9() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_10() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_11() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_12() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_13() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_14() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_15() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_16() NOP_FUNC(__LINE__);
PLACEHOLDER __place_holder_17() NOP_FUNC(__LINE__);
